<?php
const TELEGRAM_SEND_MESSAGE = "https://api.telegram.org/bot%s/sendMessage?disable_web_page_preview=true&chat_id=%s&text=%s";

/**
 * Implements hook_menu().
 * Setup the module configuration page.
 */
function telegram_post_menu()
{
  $items = array();

  $items['admin/config/services/telegram-post'] = array(
    'title' => t('Telegram post config'),
    'description' => t('Send message to telegram channel'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('telegram_post_config_form'),
    'access arguments' => array('access telegram post'),
    'file' => 'telegram_post_config.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 * Setup module permissions.
 */
function telegram_post_permission()
{
  return array(
    'access telegram item' => array(
      'title' => t('Administer telegram item'),
      'description' => t('Access permission to telegram post'),
    ),
    'telegram send message' => array(
      'title' => t('Telegram send message'),
      'description' => t('Allow user to publish updates using Telegram.'),
    ),
  );
}

/**
 * Implements hook_module_implements_alter().
 * Should be the last hook (Or at least after pathauto).
 */
function telegram_post_module_implements_alter(&$implementations, $hook)
{
  $module = basename(__FILE__, '.module');
  if (!empty($implementations[$module])) {
    $group = $implementations[$module];
    unset($implementations[$module]);
    $implementations[$module] = $group;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Add telegram elements to the form
 */
function telegram_post_form_node_form_alter(&$form, &$form_state)
{
  if (empty($form['#node']->type)) {
    return;
  }
  // Check permissions
  if (user_access('telegram send message')) {
    // Adding telegram post form
    form_load_include($form_state, 'forms.inc', 'telegram_post');
    __telegram_post_process_node_form($form);
  }
}

/**
 * Implements hook_node_insert().
 */
function telegram_post_node_insert($node)
{
  __telegram_post_process_node($node);
}

/**
 * Implements hook_node_update().
 */
function telegram_post_node_update($node)
{
  __telegram_post_process_node($node);
}

/**
 * Post the message to telegram
 */
function __telegram_post_process_node($node)
{
  $apikey = variable_get('telegram_post_apikey');
  $channel = variable_get('telegram_post_channel_name');
  $user_access = user_access('telegram send message');

  // Check whether user checked the "Post to telegram" checkbox
  $post_node = isset($node->post_to_telegram) ? $node->post_to_telegram : FALSE;

  if ($apikey && $channel && $user_access && $post_node) {
    $url = url('node/' . $node->nid, array('absolute' => TRUE, 'alias' => TRUE));
    $url_alias = url('node/' . $node->nid, array('absolute' => TRUE));
    $message = variable_get('telegram_post_default_format', 'New post: @title @url-alias');
    $message = format_string($message, array('@url' => $url, '@url-alias' => $url_alias, '@title' => $node->title));
    watchdog('telegram', "Publishing $message to $channel", array(), WATCHDOG_DEBUG, $url);
    __telegram_post_send_message($message, $apikey, $channel);
  }
}

function __telegram_post_send_message($message, $apikey, $channel)
{
  // Call Telegram API using CURL
  $curl = curl_init();
  curl_setopt($curl, CURLOPT_URL, sprintf(TELEGRAM_SEND_MESSAGE, $apikey, $channel, urlencode($message)));
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($curl, CURLOPT_HEADER, 0);
  curl_exec($curl);
  curl_close($curl);
}
